language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
  - npm install -g firebase-tools
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
  - firebase deploy --project disciply-integration --token $FIREBASE_TOKEN
