language: node_js
node_js:
  — "7"
install:
  — npm install -g firebase-tools
  — npm install -g bower
  — npm install -g polymer-cli
  — bower install
before_script:
  — npm run lint
script:
  — polymer test
  — firebase deploy --project=disciply-integration --token=${FIREBASE_TOKEN}
